In [3]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [5]:
np.random.rand(2,2)

array([[0.75777616, 0.55487361],
       [0.29791435, 0.30521133]])

In [6]:
a=np.array([4,5,6])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3,)
1
int64
8
3


In [7]:
a=np.array(1,2,3,4)

TypeError: ignored

In [8]:
a = np.array([1,2,'two',4],dtype = np.int32)
a.dtype

ValueError: ignored

In [44]:
a = np.array([1,2,'two',4])
a.dtype

dtype('<U21')

In [45]:
a = np.array([1,4,5,6,2])
print(a.max())
print(a.min())
print(a.mean())

6
1
3.6


In [46]:
a= np.array([[1,1],[2,2],[3,3]])
a.flatten()

array([1, 1, 2, 2, 3, 3])

In [47]:
np.random.randint(0,10,size=10)

array([0, 4, 1, 1, 5, 1, 9, 5, 0, 8])

In [48]:
np.array([1,2])+np.array([1,2,3])

ValueError: ignored

In [49]:
a=np.array([[1,4],[5,3]])
b=np.array([[10,20],[30,40]])
np.matmul(a,b)
a@b

array([[130, 180],
       [140, 220]])

In [50]:
a+1

array([[2, 5],
       [6, 4]])

In [51]:
a-1

array([[0, 3],
       [4, 2]])

In [52]:
a*100

array([[100, 400],
       [500, 300]])

In [53]:
a/100

array([[0.01, 0.04],
       [0.05, 0.03]])

In [54]:
a**2

array([[ 1, 16],
       [25,  9]])

In [55]:
np.arange(0.0,1.0,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [56]:
np.arange(0,10).reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
a=np.arange(0,10).reshape(5,2)
np.transpose(a)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [58]:
np.arange(0,10).reshape(3,3)

ValueError: ignored

In [59]:
ar = np.array([1,2,3,4,5])
print(np.array2string(ar,separator=","))
print(type(np.array2string(ar,separator=",")))
print(repr(ar))
print(type(repr(ar)))
print(list(ar))
print(type(list(ar)))


[1,2,3,4,5]
<class 'str'>
array([1, 2, 3, 4, 5])
<class 'str'>
[1, 2, 3, 4, 5]
<class 'list'>


In [60]:
a = np.arange(0,6).reshape(3,2)
print(a)
a.sum(axis=0)

[[0 1]
 [2 3]
 [4 5]]


array([6, 9])

##Lab11-1

In [61]:
#1번
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#2번
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#3번
np.array(range(0,10,2))

array([0, 2, 4, 6, 8])

In [64]:
#4번
c=np.array(range(0,10,2))
print("c.shape =",c.shape)
print("c.ndim =",c.ndim)
print("c.dtype =",c.dtype)
print("c.itemsize =",c.itemsize)
print("c.size =",c.size)

c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.itemsize = 8
c.size = 5


##Lab11-2

In [65]:
#1번
a = np.array([23,45,67,7,2,30,34,82])
print("a =",a)

a = [23 45 67  7  2 30 34 82]


In [66]:
#1-2번
print("최댓값 :",a.max())
print("최솟값 :",a.min())
print("평균 :",a.mean())

최댓값 : 82
최솟값 : 2
평균 : 36.25


In [67]:
#2번
b= np.array([25, 2, 9, 86, 93, 73, 15, 53, 67, 20])
print("b =",b)

print("최댓값 :",b.max())
print("최솟값 :",b.min())
print("평균 :",b.mean())

b = [25  2  9 86 93 73 15 53 67 20]
최댓값 : 93
최솟값 : 2
평균 : 44.3


In [68]:
#3번
c= np.append(a,b)
print("c = ",c)

c =  [23 45 67  7  2 30 34 82 25  2  9 86 93 73 15 53 67 20]


##Lab11-3

In [69]:
#1번
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b= np.array([[2,2,2],[2,2,2],[2,2,2]])
print("a =",a)
print("b =",b)

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [70]:
#2번
print("a+b =",a+b)
print("a-b =",a-b)
print("a*b =",a*b)
print("a/b =",a/b)
print("a@b =",a@b)#행렬 곱셈
print("a**b =",a**b)

a+b = [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a-b = [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
a*b = [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
a/b = [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
a@b = [[12 12 12]
 [30 30 30]
 [48 48 48]]
a**b = [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


##Lab11-4

In [71]:
#1번
a1 = np.full((3,3),2)
a1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [72]:
#2번
a2 = np.arange(1,13)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
#3번
a3=np.arange(0,51,3)
a3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [74]:
a4 = np.arange(0,21,5)
a4

array([ 0,  5, 10, 15, 20])

##Lab11-5

In [75]:
#1번
a1 = np.arange(1,13)
a1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [80]:
#2번
a2 = np.arange(1,31)
a2=a2.reshape(3,10)
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [77]:
#3번
a3=a2.reshape(6,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [79]:
#4번
a4 = np.transpose(a3)
a4

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

##Lab11-6

In [81]:
#1번
a = np.random.randint(1,101,size = 15)
a=a.reshape(3,5)
a

array([[98, 41, 63, 70, 38],
       [97,  5, 77, 65, 43],
       [51, 47, 49, 24, 30]])

In [82]:
#2번
print(a.max(axis=0))
print(a.min(axis=0))
print(a.mean(axis=0))


[98 47 77 70 43]
[51  5 49 24 30]
[82. 31. 63. 53. 37.]


In [83]:
#3번
print(a.max(axis=1))
print(a.min(axis=1))
print(a.mean(axis=1))


[98 97 51]
[38  5 24]
[62.  57.4 40.2]


##Lab11-7

In [84]:
#1번
a= np.arange(1,11)
b = a[1:9:2]
print("a =",a)
print("b =",b)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


In [85]:
#2번
b=a[5:]
c=a[6:]
d=a[0:3]
e = a[0::2]
f=a[-1::-2]
print("b =",b)
print("c =",c)
print("d =",d)
print("e =",e)
print("f =",f)

b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


## Lab11-8

In [86]:
#1번
a = np.arange(0,24).reshape(4,3,2)
print("index \t\t element")
for x1 in range(0,4):
    for x2 in range(0,3):
        for x3 in range(0,2):
            print("({0},{1},{2})  \t  {3}".format(x1,x2,x3,a[x1,x2,x3]))


index 		 element
(0,0,0)  	  0
(0,0,1)  	  1
(0,1,0)  	  2
(0,1,1)  	  3
(0,2,0)  	  4
(0,2,1)  	  5
(1,0,0)  	  6
(1,0,1)  	  7
(1,1,0)  	  8
(1,1,1)  	  9
(1,2,0)  	  10
(1,2,1)  	  11
(2,0,0)  	  12
(2,0,1)  	  13
(2,1,0)  	  14
(2,1,1)  	  15
(2,2,0)  	  16
(2,2,1)  	  17
(3,0,0)  	  18
(3,0,1)  	  19
(3,1,0)  	  20
(3,1,1)  	  21
(3,2,0)  	  22
(3,2,1)  	  23


In [87]:
#2번
print(np.concatenate((a[0,0],a[1,0]),axis=0))
print(np.concatenate((a[0,0],a[2,1]),axis=0))
print(np.concatenate((np.concatenate((a[0,0],a[1,0]),axis=0),np.concatenate((a[0,1],a[1,1]),axis=0),np.concatenate((a[0,2],a[1,2]),axis=0)),axis=0).reshape(3,4))

[0 1 6 7]
[ 0  1 14 15]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


##Lab11-9

In [88]:
#1번
a= np.arange(0,16).reshape(4,4)
a
b = a[:,1]
print(b)
c=a[2,1:]
print(c)
d=a[:2,:2]
print(d)
e=a[1:3,1:3]
print(e)

[ 1  5  9 13]
[ 9 10 11]
[[0 1]
 [4 5]]
[[ 5  6]
 [ 9 10]]


In [89]:
#2번
f = a[:2,:3].reshape(1,6)
print(f)
g = a[2:,:].reshape(1,8)
print(g)
h = a[1::2,1:].reshape(1,6)
print(h)

[[0 1 2 4 5 6]]
[[ 8  9 10 11 12 13 14 15]]
[[ 5  6  7 13 14 15]]


##Lab11-10

In [16]:
#1번
a = np.array([[1,1,-1],[2,-1,3],[1,2,1]], dtype = 'int32')
b = np.array([0,9,8])
x = np.linalg.solve(a,b)
print("x =",x[0],"y =",x[1],"z =",x[2])

x = 1.0 y = 2.0 z = 3.0


In [17]:
#2번
np.linalg.det(a)

-11.000000000000002

In [43]:
#3번
((1*(a[1:,1:][0,0]*a[1:,1:][1,1]-a[1:,1:][0,1]*a[1:,1:][1,0])) 
- (1*(a[1:,0::2][0,0]*a[1:,0::2][1,1]-a[1:,0::2][0,1]*a[1:,0::2][1,0])) 
- (1*(a[1:,:2][0,0]*a[1:,:2][1,1]-a[1:,:2][1,0]*a[1:,:2][0,1])))


-11